ignorePatterns:
  - '*.json'
  - '*.css'
extends:
  - standard
  - 'plugin:react/recommended'
  - airbnb
  - prettier
  - prettier/react
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  allowImportExportEverywhere: false
  ecmaFeatures:
    jsx: true
env:
  es6: true
  node: true
rules:
  indent:
    - error
    - 4
  no-underscore-dangle: 'off'
  react/prop-types: 'off'
  react/require-default-props: 'off'
  react/react-in-jsx-scope: 'off'
  react/jsx-props-no-spreading: 'off'
  react/forbid-prop-types: 'off'
  jsx-a11y/anchor-is-valid: 'off'
  jsx-a11y/click-events-have-key-events: 'off'
  jsx-a11y/no-noninteractive-element-interactions: 'off'
  jsx-a11y/no-static-element-interactions: 'off'
  jsx-a11y/media-has-caption: 'off'
  import/no-named-as-default: 'off'
  import/no-named-as-default-member: 'off'
  import/no-extraneous-dependencies: 'off'
plugins:
  - babel
  - import
  - prettier
  - react
  - react-hooks
  - standard
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
  react:
    version: detect
