name: Build

on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: NPM Install
        run: npm ci

      - name: Lint
        run: npm run linter

      - name: Next.js build
        run: npm run build && npm run export
        env:
          SECRETS_JSON: ${{ toJSON(secrets) }}

      - name: Git Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages
          FOLDER: out
          CLEAN: true
